### ISSUE TITLE
Linked List and Polynomials

### ISSUE THREAD

**Issue by Kanai2003** [KanailalManna/C-DSA#1]
# Write some code/function in C to implement the Polynomial operations using the Linked List
Polynomials like $(5x^4 + 2x^3 + 7x^2 + 10x - 8)$ can be implemented using a linked list. Every node of the linked list will have 3 parts (coefficient, exponent, and link to the next node). Assume that the exponent of each successive term is less than that of the previous term.
``` 
typedef struct polynode{        //use this structure concept to implement your functions
      float coeff;
      int exp;
      struct polynode *link;
}polynode;
```
## Create functions: 
- ` poly_append() `    -> Append a node in a linked list with the value of coefficient and exponent which is taken from user input.
- ` display_poly() `    -> Display the polynomial. Format:  5x^4 : 2x^3 : 7x^2 : 10x - 8
- ` poly_add() `    -> Add two polynomials and store it in a polynomial. poly1: $3x^2 + 2x + 5$, poly2: $2x^2 + 2$, Result: $5x^2 + 2x + 7$
- ` poly_multiply() `    -> Multiply two polynomials and store it in a polynomial. poly1: $3x^5 + 2x^4 + 1x^2$, poly2: $1x^6 + 2x^5 + 3x^4$, Result: $3x^{11} + 8x^{10} + 13x^9 + 7x^8 + 2x^7 + 3x^6$
## Rules: 
- Warning!!! :  don't ctrl+c and ctrl+v code from internet
- Modify the  https://github.com/KanailalManna/C-DSA/blob/master/LinkedList/Polynomial.c   file 
- Comment below if you want to be assigned to this issue (then start working on the issue)

**Comment by abhinavjoshicse** [comment]
hey! I would like to contribute in this, please assign this issue to me.
thank you!

**Comment by Kanai2003** [comment]
sure

**Comment by Kanai2003** [comment]
complete within 48 hrs.

**Comment by Kanai2003** [comment]
Hey, how it's going on?

**Comment by Faizan96322** [comment]
hey, if @Abhinav-J05 is not working on this problem can you pls assign me this repo, I would like to contribute my code in it!

**Comment by abhinavjoshicse** [comment]
apologies for being late, work is in progress... just need some more time

**Comment by Kanai2003** [comment]
Ok

**Comment by Kanai2003** [comment]
I'm also assigning @Faizan96322

**Comment by SOHAMmondal2003** [comment]
assigned me this issue

**Comment by Kanai2003** [comment]
Okay
