### ISSUE TITLE
Build Tree

### ISSUE THREAD

**Issue by Kanai2003** [KanailalManna/C-DSA#14]
# Write a program in C to build tree and traverse 

## Functions:
- InsertLeft()
- InsertRight()
- InorderTraversal()
- PreOrderTraversal
- PostOrderTraversal()
- You can build any function as you wish
## Rules:
- Modify https://github.com/KanailalManna/C-DSA/blob/master/Tree/BinaryTree.c file

**Comment by PALSAMIRAN** [comment]
Please assign  me this issue

**Comment by Kanai2003** [comment]
Okay
