### ISSUE TITLE
Sorting & Linked List 

### ISSUE THREAD

**Issue by Kanai2003** [KanailalManna/C-DSA#3]
# Write code/function to sort a linked list 
## Instructions:
- Build functions to sort the linked list 
- You can also edit my code to improve
## Rules:
- Modify the  https://github.com/KanailalManna/C-DSA/blob/master/LinkedList/SortLL.c file
- Warning!!! : Don't ctrl+c and ctrl+v from the internet 
-  Comment below if you want to be assigned to this issue (then start working on the issue)

**Comment by Yash-Goyal007** [comment]
Would you like to assign this issue to me as I really want to contribute..

**Comment by Kanai2003** [comment]
Ok, I'm assigning you, complete within 24 hrs.
