### ISSUE TITLE
Queue Using Linked List

### ISSUE THREAD

**Issue by Kanai2003** [KanailalManna/C-DSA#5]
# Write the main function in c to maintain the whole code 
## Instructions:
Modify the ` main() ` function to access the whole code 
```
1. Insert    2. Delete     3. Display     4. Exit     
Enter your choice:
```
## Rules: 
- Warning!!! :  don't ctrl+c and ctrl+v code from the internet
- Modify the  https://github.com/KanailalManna/C-DSA/blob/master/Queue/QueueUsingLinkedList.c   file 
- Comment below if you want to be assigned to this issue (then start working on the issue)

**Comment by SubiditaB** [comment]
please assign me this issue

**Comment by Kanai2003** [comment]
okey
complete within 48 hrs

**Comment by MehrotrajiWebsiting** [comment]
please assign me this issue

**Comment by manipta** [comment]
hello!!
please assign me with this issue.
thanks :)
