### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by Kanai2003** [KanailalManna/C-DSA#9]
# Make a Calendar using C which will take a year as input and give the output as its monthly calendar.
## Rules:
- don't copy and paste from the internet
- Modify https://github.com/KanailalManna/C-DSA/blob/master/Basic_Problem_Practice/Calendar.c file

**Comment by Panchojanyya** [comment]
plz assign me this issue

**Comment by Subhojit666** [comment]
Sir , this is my first time in hactoberfest. Please assign me this.

**Comment by Aishaa-26** [comment]
@KanailalManna Request you to please assign this issue to me.

**Comment by Kanai2003** [comment]
Okay I'm assigning you all

**Comment by Panchojanyya** [comment]
plz assign me this problem its my earnest request

**Comment by anujguha** [comment]
Hey! I would love to work on this. Please assign me this...
